language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.3

before_script:
  - composer require --dev php-coveralls/php-coveralls
# The following lines will not be needed once there are public repositories, but while this is still private:
  - composer config repositories.console-helpers '{"type":"vcs","url":"git@github.com:acquia/console-helpers.git","no-api":true}'
  - composer install

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - vendor/bin/phpcs -n --standard=Drupal,DrupalPractice src/ tests/